version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6100:6100"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_NAME=dev-api-user
      - DB_NAME_PROD=dev-api-user
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
